import { ProjectSetupWizardData } from '../../types/wizard';

export const mockTemplateData: ProjectSetupWizardData = {
  projectInfo: {
    projectCode: 'PRJ-NEOM-WEST-01',
    projectName: 'مشروع ناقلات نيوم - قطاع ركام البنية التحتية',
    clientName: 'شركة نيوم للتطوير العقاري واللوجستي',
    description: 'إدارة أسطول النقل الثقيل، موازين الشاحنات، وتوريد مواد الردم والخرسانة المسلحة لمشروع البنية التحتية الشمالي.',
    status: 'ACTIVE',
    startDate: '2026-09-01',
    endDate: '2027-12-31',
    defaultSettings: {
      currency: 'SAR',
      vatRatePercent: 15,
      zatcaTaxNumber: '301234567800003',
      requireTareOnExit: true,
      maxToleranceKg: 500,
      allowDriverSelfDispatch: false,
      addressAr: 'منطقة تبوك - قطاع العمليات اللوجستية 4',
      geoFenceRadiusMeters: 2000,
    },
  },
  materials: [
    {
      id: 'mat-1',
      materialId: 'MAT-SB-CLASS-A',
      materialName: 'ركام طبقة أساس (Sub-base Class A)',
      materialCode: 'SB-01',
      unitOfMeasure: 'TON',
      status: 'ACTIVE',
      sortOrder: 1,
      standardDensityTonPerM3: 2.1,
    },
    {
      id: 'mat-2',
      materialId: 'MAT-WASHED-SAND',
      materialName: 'رمل أحمر مغسول ناعم',
      materialCode: 'SND-02',
      unitOfMeasure: 'TON',
      status: 'ACTIVE',
      sortOrder: 2,
      standardDensityTonPerM3: 1.6,
    },
    {
      id: 'mat-3',
      materialId: 'MAT-GRAVEL-34',
      materialName: 'بحص خرساني مقاس 3/4 إنش',
      materialCode: 'GRV-03',
      unitOfMeasure: 'TON',
      status: 'ACTIVE',
      sortOrder: 3,
      standardDensityTonPerM3: 1.55,
    },
    {
      id: 'mat-4',
      materialId: 'MAT-BACKFILL-M3',
      materialName: 'تربة دفان صخرية عامة',
      materialCode: 'BKF-04',
      unitOfMeasure: 'M3',
      status: 'DISABLED',
      sortOrder: 4,
      standardDensityTonPerM3: 1.8,
    },
  ],
  carriers: [
    {
      id: 'car-1',
      carrierId: 'CAR-A',
      carrierName: 'شركة الرشيد للخدمات اللوجستية (Carrier A)',
      commercialRegistrationNo: '1010234567',
      transportLicenseNo: 'TGA-LOG-44910',
      status: 'ACTIVE',
      contactPersonName: 'م. فهد الرشيد',
      contactPhone: '+966551234567',
      contactEmail: 'f.alrashid@alrashid-log.sa',
    },
    {
      id: 'car-2',
      carrierId: 'CAR-B',
      carrierName: 'مؤسسة الصفا للنقل الثقيل (Carrier B)',
      commercialRegistrationNo: '1010876543',
      transportLicenseNo: 'TGA-LOG-55821',
      status: 'ACTIVE',
      contactPersonName: 'أ. خالد الصفا',
      contactPhone: '+966509876543',
      contactEmail: 'khalid@alsafa-transport.com',
    },
    {
      id: 'car-3',
      carrierId: 'CAR-C',
      carrierName: 'شركة الجميح للشاحنات والمقاولات (Carrier C)',
      commercialRegistrationNo: '1010332211',
      transportLicenseNo: 'TGA-LOG-66732',
      status: 'ACTIVE',
      contactPersonName: 'أ. سامي الجميح',
      contactPhone: '+966541122334',
      contactEmail: 'sami@aljomaih-haulage.sa',
    },
  ],
  pricingRules: [
    // Carrier A -> PER_TRIP -> 120 SAR
    {
      id: 'pr-1',
      pricingRuleId: 'PR-CAR-A-TRIP-120',
      carrierId: 'CAR-A',
      pricingType: 'PER_TRIP',
      rate: 120,
      currency: 'SAR',
      effectiveFrom: '2026-09-01',
      effectiveTo: '2027-12-31',
      materialId: 'ALL_MATERIALS',
      notes: 'اتفاقية مقطوعة بالرد الواحد لجميع المواد داخل النطاق',
      vatApplicable: true,
      demurrageRatePerHourSAR: 60,
      freeTimeHours: 2,
    },
    // Carrier B -> PER_TON -> 8.5 SAR
    {
      id: 'pr-2',
      pricingRuleId: 'PR-CAR-B-TON-8-5',
      carrierId: 'CAR-B',
      pricingType: 'PER_TON',
      rate: 8.5,
      currency: 'SAR',
      effectiveFrom: '2026-09-01',
      effectiveTo: '2027-12-31',
      materialId: 'ALL_MATERIALS',
      notes: 'حساب بالطن الصافي لجميع التوريدات مع وزن إلزامي في الميزان',
      vatApplicable: true,
      demurrageRatePerHourSAR: 50,
      freeTimeHours: 2,
    },
    // Carrier C -> PER_TON -> 7.75 SAR
    {
      id: 'pr-3',
      pricingRuleId: 'PR-CAR-C-TON-7-75',
      carrierId: 'CAR-C',
      pricingType: 'PER_TON',
      rate: 7.75,
      currency: 'SAR',
      effectiveFrom: '2026-09-01',
      effectiveTo: '2027-12-31',
      materialId: 'ALL_MATERIALS',
      notes: 'تسعيرة مخفضة خاصة بالكميات الكبيرة من الركام',
      vatApplicable: true,
      demurrageRatePerHourSAR: 45,
      freeTimeHours: 2.5,
    },
  ],
  userAccess: [
    {
      userId: 'USR-ADMIN-01',
      fullName: 'م. راكان الراجحي',
      email: 'rakan.alrajhi@q-saudi.sa',
      role: 'PROJECT_ADMIN',
      isAssigned: true,
    },
    {
      userId: 'USR-DISP-01',
      fullName: 'سعد القحطاني',
      email: 'saad.disp@q-saudi.sa',
      role: 'DISPATCHER',
      isAssigned: true,
    },
    {
      userId: 'USR-AUDIT-01',
      fullName: 'نورة السبيعي',
      email: 'noura.finance@q-saudi.sa',
      role: 'FINANCE_AUDITOR',
      isAssigned: true,
    },
    {
      userId: 'USR-VIEW-01',
      fullName: 'مراقب العمليات الميدانية',
      email: 'field.viewer@q-saudi.sa',
      role: 'VIEWER',
      isAssigned: false,
    },
  ],
  googleDrive: {
    enabled: true,
    rootFolderName: 'PRJ-NEOM-WEST-01 - أرشيف ومستندات المشروع',
    provisionSpreadsheet: true,
    spreadsheetTitle: 'سجل رحلات وموازين مشروع نيوم اللوجستي 2026',
    autoSyncTickets: true,
    archiveDailyTrips: true,
    folderStructure: [
      '01_سجلات_الرحلات_اليومية',
      '02_تذاكر_الميزان_الرقمية_PDF',
      '03_مطابقات_فواتير_الناقلين',
      '04_تقارير_مراقبة_الجودة_والاستثناءات',
    ],
    generatedFolderId: 'gdrive-folder-neom-west-01',
    generatedSpreadsheetId: 'gsheet-neom-west-01-trips',
  },
};

export const INITIAL_EMPTY_WIZARD_DATA = mockTemplateData;
