/**
 * Import Center & Import Batch Type Definitions
 * 12-Stage Pipeline with Human Correction and Pre-Commit Enforcement
 */

export type ImportStage =
  | 'UPLOAD'                 // 1. Upload
  | 'PARSE'                  // 2. Parse
  | 'DETECT_COLUMNS'         // 3. Detect Columns
  | 'NORMALIZE'              // 4. Normalize
  | 'MATCH_ENTITIES'         // 5. Match Entities
  | 'VALIDATE_RELATIONSHIPS' // 6. Validate Relationships
  | 'DETECT_DUPLICATES'      // 7. Detect Duplicates
  | 'GENERATE_REPORT'        // 8. Generate Review Report
  | 'HUMAN_CORRECTION'       // 9. Human Correction (PAUSE POINT)
  | 'FINAL_VALIDATION'       // 10. Final Validation
  | 'COMMIT'                 // 11. Commit
  | 'AUDIT';                 // 12. Audit

export type ReviewActionType =
  | 'ACCEPT_SUGGESTION'      // Accept Suggestion (قبول الاقتراح)
  | 'KEEP_ORIGINAL'          // Keep Original (الإبقاء على الأصل)
  | 'CHOOSE_MASTER_RECORD'   // Choose Master Record (اختيار سجل مرجعي)
  | 'EDIT_MANUALLY'          // Edit Manually (تعديل يدوي)
  | 'IGNORE'                 // Ignore (تجاهل)
  | 'REJECT_ROW';            // Reject Row (استبعاد الصف)

export type IssueSeverity = 'CRITICAL' | 'WARNING' | 'INFO';

export interface ReviewTableRow {
  id: string;                // Unique review row item ID
  rowNumber: number;         // 1-based index in the source file
  field: string;             // Human readable field name (الناقل، الشاحنة، السائق، المادة...)
  fieldKey: 'carrier' | 'truck' | 'driver' | 'material' | 'tareKg' | 'grossKg' | 'waybill' | 'date';
  originalValue: string;     // Original Value (القيمة الأصلية)
  suggestedValue: string;    // Suggested Value (القيمة المقترحة)
  confidence: number;        // Confidence (0-100%)
  issue: string;             // Issue description (طبيعة المشكلة والتعارض)
  severity: IssueSeverity;   // Severity (CRITICAL, WARNING, INFO)
  action: ReviewActionType;  // Action selected by user or default
  
  // Custom action payloads
  chosenMasterId?: string;
  chosenMasterValue?: string;
  manualValue?: string;
  notes?: string;

  // Status of the entire source row
  rowStatus: 'ACTIVE' | 'REJECTED';
  rawRowData: Record<string, any>;
}

export interface ImportBatchAuditLogEntry {
  timestamp: string;
  userId: string;
  userName: string;
  actionType: string;
  detailsAr: string;
  affectedRowNumber?: number;
  previousValue?: any;
  newValue?: any;
}

export interface ImportBatch {
  importBatchId: string;
  projectId: string;
  fileName: string;
  uploadedBy: string;
  createdAt: string;
  rowCount: number;
  validCount: number;
  warningCount: number;
  errorCount: number;
  status: 'DRAFT' | 'ANALYZED' | 'AWAITING_CORRECTION' | 'READY_TO_COMMIT' | 'COMMITTED' | 'REJECTED';
  
  // Stored original data for audit retention
  originalRawData: Record<string, any>[];
  
  // Review rows generated by report
  reviewItems: ReviewTableRow[];
  
  // Current stage in the 12-stage pipeline
  currentStage: ImportStage;
  
  // Audit trail of human decisions
  auditTrail: ImportBatchAuditLogEntry[];
  
  // Warning confirmation block
  warningConfirmation?: {
    confirmed: boolean;
    confirmedBy: string;
    confirmedAt: string;
    notes?: string;
  };

  committedAt?: string;
  committedBy?: string;
  committedRecordCount?: number;
}

// Re-export Unified Import Domain Model (BLOCK 30 & 31)
export * from './unifiedImport';
export * from './excelCsvImport';
